language: python
python:
- '3.4'
env:
- MEERKAT_ABACUS_DB_URL='postgresql+psycopg2://postgres:postgres@localhost/meerkat_db'
addons:
  postgresql: '9.4'
services:
- postgresql
install:
- pip install -r requirements.txt
script: nosetests
notifications:
  slack:
    secure: M3cDy+WfJMohLYeNGricQZdHdTfoRqLRFhxTrQdnW5PRshrtK7bTLIvENxypSQesjTjSeMRPpfepO86EUn3NZoak/FQD4nNhHI2LKwjNco//6WuEOgtiSpb1MNESz8CZHItZqidi/PRRSRCWP7xcfACNwZy4MvnoURt4sUHdbgHa+/Cw1VhYxPDD+7I2u9ouRwcSgyHcFlvYXIztFughGizrUsYMsQjKMo4R54P/UsyyAaHCrHklJUjGTzu1NgdeOhG/3QSMVhVVc+8qMHmJwBSM3+YzguLO8oo97hx6Ow362jym0Bk6QJBBXUSpWvmqngZnj/N0XhbGsDmf2w3rQOMj2PIiDO0gR91l/p3uhH0TJW0fo174WmWoK5Ri2SS8lmwHP8F7db6npwtMPRLOHu+djQDW0UYLFH3598I+c/3MigZ5t2NDar9l223cSY9gmOaCGpSiVPolYirrWxxvmBXV9nmiaTtvt5ykCLFQI1KHH1JRJDi/FlST40F16bB8GhGzfKSxl8Ar9mPvSjg5QNTOsKDgG9ZGKVsuhzJcVi0/lyvEKIU3Qx3mVMBuw4iuBWMx4UdqX3BA3rLJlRy1S9yL1iLKGX7esJJ9V/COSHWljsg4eSV1Ynkrs35mFPH6zN4AQ+1XmQy8G++/i5gEJU3HT0W+nLTBfMBmUc/hWs0=
